# Generated by Django 5.2 on 2025-04-24 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('hours', models.JSONField(blank=True, null=True)),
                ('photo_reference', models.CharField(blank=True, help_text='Reference token for retrieving a photo via Google Places API', max_length=255)),
                ('price_level', models.PositiveSmallIntegerField(blank=True, help_text='Price level from 0 (free) to 4 (very expensive)', null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average rating from Google (e.g., 4.3)', max_digits=3, null=True)),
                ('type', models.CharField(default='bar', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_bars', models.ManyToManyField(blank=True, to='backend.bar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estimated_wait', models.PositiveIntegerField(help_text='Estimated wait time in minutes')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wait_times', to='backend.bar')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='backend.bar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'bar')},
            },
        ),
    ]
