# Generated by Django 5.2 on 2025-04-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_bars',
        ),
    ]
