# Generated by Django 5.2 on 2025-05-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_bar_photo_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='photo_reference',
            field=models.CharField(blank=True, help_text='Reference token for retrieving a photo via Google Places API', max_length=1000),
        ),
    ]
