# Generated by Django 5.0.11 on 2025-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_bar_photo_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Is the bar currently open?'),
        ),
    ]
