# Generated by Django 5.2.1 on 2025-05-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_bar_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Is the bar currently open?'),
        ),
    ]
