# Generated by Django 5.2.1 on 2025-05-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_bar_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_over_21',
            field=models.BooleanField(default=False, help_text='Whether the user is 21+'),
        ),
    ]
