# Generated by Django 5.0.11 on 2025-05-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_userprofile_is_over_21'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='type',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
