# Generated by Django 5.0.11 on 2025-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_bar_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='type',
            field=models.CharField(default='bar', max_length=50),
        ),
    ]
